pipeline {
    environment {
    registry = "48662523/python-app"
    dockerImage = ''
    registryCredential = 'dockerhub'
    }
    agent any
    stages {
        stage('Build') { 
            steps {
                dir('FlaskApp'){
                    script {
                        dockerImage = docker.build registry + ":$BUILD_NUMBER"
                        }
                    }
                }
            }

        stage('Push') {
            steps{
                script {
                    docker.withRegistry( '', registryCredential ) {
                        dockerImage.push()
                        }
                    }
                }
            }

        stage('Clean') {
            steps{
                sh "docker rmi $registry:$BUILD_NUMBER"
                sh "docker rmi alpine:latest"
                sh "docker images"
                }
            }
    }

    post {
        always {
            cleanWs()
        }
    }
}