pipeline {
    environment {
    registry = "python-app"
    dockerImage = '' 
    }
    agent any
    stages {
        stage('Build') { 
            steps {
                dir('FlaskApp'){
                    script {
                        dockerImage = docker.build registry
                        }
                    }
                }
            }

        stage('Clean') { 
            steps { 
                sh "docker rmi $registry:latest"
                sh "docker rmi alpine:latest"
            }
        }

        stage('check'){
            steps {
                sh 'docker images'
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}